    // Login actions

export const LOGIN_PROP_CHANGED     = 'LOGIN_PROP_CHANGED'
export const LOGIN_PROP_ERROR       = 'LOGIN_PROP_ERROR'
export const LOGIN_SUBMIT_STARTED   = 'LOGIN_SUBMIT_STARTED'
export const LOGIN_SUBMIT_SUCCES    = 'LOGIN_SUBMIT_SUCCES'
export const LOGIN_SUBMIT_FAILED    = 'LOGIN_SUBMIT_FAILED'
export const SET_USER_OBJECT        = 'SET_USER_OBJECT'
export const LOG_OUT                = 'LOG_OUT'


// Signup actions

export const SIGNUP_PROP_CHANGED        = 'SIGNUP_PROP_CHANGED'
export const SIGNUP_PROP_ERROR          = 'SIGNUP_PROP_ERROR'
export const SIGNUP_SUBMIT_STARTED      = 'SIGNUP_SUBMIT_STARTED'
export const SIGNUP_SUBMIT_SUCCES       = 'SIGNUP_SUBMIT_SUCCES'
export const SIGNUP_SUBMIT_FAILED       = 'SIGNUP_SUBMIT_FAILED'
export const SIGNUP_GET_CITY_STARTED    = 'SIGNUP_GET_CITY_STARTED'
export const SIGNUP_GET_CITY_SUCCESS    = 'SIGNUP_GET_CITY_SUCCESS'
export const SIGNUP_GET_CITY_FAILED     = 'SIGNUP_GET_CITY_FAILED'


//cities
export const FETCH_CITIES_STARTED   = 'FETCH_CITIES_STARTED'
export const FETCH_CITIES_FAILED    = 'FETCH_CITIES_FAILED'
export const FETCH_CITIES_SUCCESS   = 'FETCH_CITIES_SUCCESS'


//events actions
export const FETCH_EVENTS_STARTED       = 'FETCH_EVENTS_STARTED'
export const FETCH_EVENTS_SUCCESS       = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILED        = 'FETCH_EVENTS_FAILED'

//categories actions
export const FETCH_CATEGORIES_STARTED   = 'FETCH_CATEGORIES_STARTED'
export const FETCH_CATEGORIES_SUCCESS   = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILED    = 'FETCH_CATEGORIES_FAILED'
export const CLEAN_UP_CATEGORIES        = 'CLEAN_UP_CATEGORIES'
export const REFRESH_CATEGORIES         = 'REFRESH_CATEGORIES'
export const PAGINATE_CATEGORIES_DATA   = 'PAGINATE_CATEGORIES_DATA'

//services actions
export const FETCH_SERVICES_STARTED   = 'FETCH_SERVICES_STARTED'
export const FETCH_SERVICES_SUCCESS   = 'FETCH_SERVICES_SUCCESS'
export const FETCH_SERVICES_FAILED    = 'FETCH_SERVICES_FAILED'
export const CLEAN_UP_SERVICES        = 'CLEAN_UP_SERVICES'
export const REFRESH_SERVICES         = 'REFRESH_SERVICES'
export const PAGINATE_SERVICES_DATA   = 'PAGINATE_SERVICES_DATA'
export const CHANGE_SELECTED_SERVICES = 'CHANGE_SELECTED_SERVICES'