export default ar = {
  password: "الرقم السرى",
  noInternetConnection: "لا يوجد إتصال بالإنترنت",
  login: "تسجيل الدخول",
  loginEnjoy: "سجل دخولك لتستمتع",
  createAcc: "انشاء حساب جديد",
  home: "الرئيسية",
  dontHaveAnAccount: "لا تملك حساب ؟",
  signup: "التسجيل",
  confirm: "تأكيد",
  save: "حفظ",
  cancel: "إلغاء",
  yes: "نعم",
  selectTime: "إختر الوقت",
  edit: "تعديل",
  update: "تحديث",
  preferredLanugage: "اللغة المفضلة",
  english: "English",
  arabic: "العربية",
  no: "لا",
  passwordConfirmation: "تأكيد الرقم السرى",
  email: "البريد الإلكترونى",
  logout: "تسجيل الخروج",
  forgotPasswordQues: "نسيت كلمة المرور ؟",
  resetPassword: "إسترجاع كلمة المرور",
  yourName: "اسمك",
  phoneNumber: "رقم التليفون",
  male: "ذكر",
  female: "انثى",
  city: "المدينة",
  youHaveAcc: "انت تمتلك حساب!",
  loginNow: "سجل دخولك الان",
  signupNow: "سجل عضويه الان",
  welcome: "مرحبا",
  homePharase: "ما الذي تبحث عنه اليوم في ايفنت فول !",
  service: "خدمة",
  event: "حدث",
  ourServiceIn: "خدماتنا في",
  selectServiceYouNeed: "حدد الخدمة التي ترغب بها",
  specialOffer: "عرض خاص",
  submit: "اطلب",
  selectYourOffer: "اختر عرضك بما يتناسب مع طلبك عن طريق اكمال النموذج أدناه",
  approtType: "النوع مناسب",
  budget: "الميزانية",
  fromRs: "من (ريال سعودى)",
  toRs: "الى (ريال سعودى)",
  address: "العنوان",
  notes: "ملاحظات",
  selectServiceYouWish: "حدد الخدمات التي ترغب في الحصول عليها",
  viewProfile: "عرض الصفحة الشخصية",
  providers: "مقدمي الخدمات",
  providerData: "بيانات مقدم الخدمة",
  details: "تفاصيل",
  services: "خدمات",
  priceRange: "نطاق السعر:",
  serviceData: "بيانات الخدمة",
  photos: "البوم الصور",
  location: "الموقع",
  getDirection: "احصل على اتجاه",
  booking: "احجز",
  events: "أحداث",
  eventsPhase: "استمتع وانضم الى المناسبات",
  eventsRecently: "المناسبات المضافة مؤخرا",
  musicParty: "الحفلات الموسيقية",
  bookingNow: "احجز الان",
  add: "إضافة",
  // profile
  ignore: "تجاهل",
  providerResponse: "استجابة المزود",
  offerData: "البيانات الخاص",
  DateTime: "التاريخ  الوقت",
  appropriatetype: "نوع مناسب",
  PersonalData: "بيانات شخصية",
  ChangePassword: "تغيير كلمة السر",
  paymentInfo: "معلومات الدفع",
  paymentInfo2: "معاملاتك المالية",
  creditName: "إسم المستخدم",
  CardNumber: "رقم البطاقة",
  cardtype: "نوع البطاقة",
  expirationDate: "تاريخ إنتهاء الصلاحية",
  month: "MM",
  Year: "YYYY",
  numOfComments: "تعليق {0}",
  reviews: "تعليقات",
  addReview: "اضافة تعليق",
  templates: "قوالب",
  templatesPhase: "يمكنك دعوة أي شخص إلى المناسبة",
  editTemplates: "تعديل القالب",
  invitation: "دعوات",
  mainTitle: "العنوان الرئيسي",
  invitationText: "نص الدعوة",
  invitationDate: "تاريخ الدعوة",
  telephone: "رقم الهاتف",
  ownerOfInvitation: "صاحب الدعوة",
  addFriends: "اضف اصدقائك",
  view: "شاهد",
  viewTemplates: "عرض القالب",
  share: "مشاركة",
  language: "اللغة",
  english: "الإنجليزية",
  arabic: "عربى",
  aboutApp: "حول التطبيق",
  aboutDev: "عن المطور",
  termsAndCond: "الأحكام والشروط",
  customerService: "خدمة العملاء",
  settings: "الإعدادات",
  langPhase: "اختر لغة التطبيق",
  contactUs: "تواصل معنا",
  termsPhase: "الأحكام والشروط",
  termsRead: "اقرأ شروط الاستخدام التالية بعناية قبل استخدام هذا التطبيق.",
  message: "الرسالة",
  customerPhase: "ابق على اتصال معنا وإخبارنا بتعليقاتك وشكاواك",
  forgetPasswordPhase: "أدخل بريدك الإلكتروني وسنرسل لك رمز تأكيد لتعيين كلمة المرور الخاصة بك",
  forgetPassword: "نسيت كلمة المرور",
  confirmationCode: "تأكيد الكود",
  confirmPhase: "تم إرسال رمز التأكيد الخاص بك. يرجى التحقق من البريد الوارد",
  sendCode: "إرسال رمز",
  confirmCode: "تأكيد الكود",
  sendCodeAgain: "ارسل الرمز مجددا",
  newPassword: "كلمة السر الجديدة",
  enterNewPass: "الرجاء إدخال كلمة المرور الجديدة",
  organizers: "المنظمون",
  eventData: "معلومات عن المناسبة",
  book: "احجز",
  seeAll: "عرض الكل",
  yourPurches: "مشترياتك",
  serviceTotal: "اجمالى الخدمات",
  eventTicketesTotal: "اجمالى تذاكر المناسبات",
  orderTotal: "اجمالى الطلب",
  payWith: "الدفع بواسطه",
  addNewPayment: "اضافه وسيلة دفع جديدة",
  basket: "سله الحجوزات",
  goTo: "اذهب الى",
  notifications: "الاشعارات",
  search: "ابحث",
  almostDone: 'يكاد ينتهي',
  yourOrderAdded: 'تمت إضافة طلبك إلى السلة',
  gotoCard: 'الذهاب إلى السلة',
  keepBrowsing: 'استمر في التصفح',
  bookingFor: 'الحجز ل',
  orderMadeTo: 'سيتم الحجز الى: ',
  forFemale: 'للإناث فقط',
  forMale: 'للذكور فقط',
  next: 'التالى',
  share: 'شارك مع',
  asInvitation: 'مثل دعوة',
  or:'أو',
  audioList: 'قائمة الالبومات',
  albums: 'الالبومات',
  simmilerAlbums: 'ألبومات مماثلة',
  giveReview: 'إعطاء مراجعة',
  reviewPhase: 'يمكنك تقييم باستخدام النجوم',
  reviewLabel: 'إخبرنا المزيد',
  writeComment: 'أكتب تعليقا',
  thankYou: 'شكرا جزيلا',
  successProcess: 'عملية ناجحة',
  billDate: 'تاريخ الفاتورة',
  time: 'وقت الفاتورة',
  total: 'مجموع',
  oprationNum: 'رقم العملية',
  done: 'تم',
  RS: '{0} ر.س',
  likeCount: 'معجب {0}',
  joinCount: 'منضم {0}',
  reload: 'إعادة تحميل',
  noServicesFound: 'لا توجد خدمات متاحه'
};
