export default (en = {
  noInternetConnection: "No internet connection",
  password: "Password",
  login: "Login",
  home: "Home",
  dontHaveAnAccount: "Don't have an account ?",
  signup: "Sign Up",
  loginEnjoy: "Login To enjoy",
  createAcc: "Create a New account",
  forgotPasswordQues: "Forgot password!",
  location: "Location",
  confirm: "Confirm",
  chooseDate: "Choose appointment day",
  save: "Save",
  cancel: "Cancel",
  pleaseSelectTime: "Please select a time",
  edit: "Edit",
  update: "Update",
  preferredLanugage: "Preferred Lanugage",
  english: "English",
  arabic: "العربية",
  yes: "Yes",
  no: "No",
  email: "Email Address",
  yourName: "Your Name",
  phoneNumber: "Phone Number",
  male: "Male",
  female: "Female",
  city: "City",
  youHaveAcc: "You have an account!",
  loginNow: "Login Now",
  signupNow: "Sign up Now",
  passwordConfirmation: "Confirm Password",
  welcome: "Welcome",
  homePharase: "What you Looking for Today in Eventful !",
  service: "Service",
  event: "Event",
  ourServiceIn: "Our Services in",
  selectServiceYouNeed: "Select the service you would like to receive",
  specialOffer: "Special Offer",
  submit: "Submit",
  selectYourOffer:
    "Choose your offer as appropriate for your order by filling out the form below",
  approtType: "Appropriate type",
  budget: "Budget",
  fromRs: "from RS",
  toRs: "to RS",
  address: "Address",
  notes: "Notes",
  add: "ADD",
  //Profile
  ignore: "Ignore",
  providerResponse: "Provider Response",
  offerData: "Your Offer Data",
  appropriatetype: "Appropriate type",
  DateTime: "Date  Time",
  editProfile: "EditProfile",
  AcceptRequest: "Accept Request",
  profile: "Profile",
  PersonalData: "Personal Data",
  ChangePassword: "Change Password",
  paymentInfo: "Payment Info",
  selectServiceYouWish: "Select Services You Wish to get",
  viewProfile: "View Profile",
  providers: "Providers",
  providerData: "Provider Data",
  details: "Details",
  services: "Services",
  priceRange: "price range:",
  serviceData: "Service Data",
  photos: "Photos",
  location: "Location",
  getDirection: "Get Direction",
  booking: "Booking",
  events: "Events",
  eventsPhase: "Enjoy and join to Events",
  eventsRecently: "Events Recently added",
  musicParty: "Music Party",
  bookingNow: "Booking now",
  selectServiceYouWish: "Select Services You Wish to get",
  viewProfile: "View Profile",
  providers: "Providers",
  providerData: "Provider Data",
  details: "Details",
  services: "Services",
  priceRange: "price range:",
  serviceData: "Service Data",
  photos: "Photos",
  location: "Location",
  getDirection: "Get Direction",
  booking: "Booking",
  paymentInfo2: "Your Payment Info",
  creditName: "Credit name",
  CardNumber: "Card Number",
  cardtype: "card type",
  expirationDate: "Expiration Date",
  month: "MM",
  Year: "YYYY",
  numOfComments: "{0} comments",
  reviews: "Reviews",
  addReview: "Add Review",
  templates: "Templates",
  templatesPhase: "You can invite anyone to Event",
  editTemplates: "Edit Template",
  invitation: "Invitations",
  mainTitle: "Main Title",
  invitationText: "Invitation Text",
  invitationDate: "Invitation Date",
  telephone: "Telephone",
  ownerOfInvitation: "The owner of the invitation",
  addFriends: "Add Your Friends",
  view: "View",
  viewTemplates: "View Template",
  share: "Share",
  language: "Language",
  english: "English",
  arabic: "Arabic",
  aboutApp: "About Application",
  aboutDev: "About the developer",
  termsAndCond: "Terms And Conditions",
  customerService: "customers service",
  settings: "Settings",
  langPhase: "Choose the Language of Application",
  contactUs: "Contact with us",
  termsPhase: "Terms And Conditions",
  termsRead:
    "Read the following Terms of Use carefully before using this Application.",
  message: "Message",
  customerPhase:
    "Stay in touch with us and let us know your comments and complaints",
  forgetPasswordPhase:
    "Enter your email and we'll send you a confirmation code to set your password",
  forgetPassword: "Forget Password",
  confirmationCode: "Confirmation Code",
  confirmPhase: "Your confirmation code has been sent. Please check your inbox",
  sendCode: "Send code",
  confirmCode: "Confirm Code",
  sendCodeAgain: "Send Code Again",
  newPassword: "New Password",
  enterNewPass: "Please Enter Your New Password",
  organizers: "Organizers",
  eventData: "Event data",
  book: "Book",
  seeAll: "See All",
  yourPurches: "Your Purchase",
  serviceTotal: "Service total",
  eventTicketesTotal: "Event Ticket Total",
  orderTotal: "Order total",
  payWith: "Pay With",
  addNewPayment: "Add New Payment info",
  basket: "Basket",
  goTo: "Go to",
  notifications: "Notifications",
  search: "Search",
  almostDone: 'Almost Done',
  yourOrderAdded: 'Your Order added to Your Card',
  gotoCard: 'Go to card',
  keepBrowsing: 'keep browsing',
  bookingFor: 'Booking For',
  orderMadeTo: 'Your reservation will be made to :',
  forFemale: 'For Female only',
  forMale: 'For Male only',
  next: 'Next',
  share: 'Share With',
  asInvitation: 'as  Invitation',
  or:'or',
  audioList: 'Audio List Album',
  albums: 'Albums',
  simmilerAlbums: 'Simmilar Albums',
  giveReview: 'Give A Review',
  reviewPhase: 'You Can Rate by Use the Stars',
  reviewLabel: 'Tell Us More',
  writeComment: 'Write a Comment',
  thankYou: 'Thank You',
  successProcess: 'Successful process',
  billDate: 'Bill Date',
  time: 'Time',
  total: 'Total',
  oprationNum: 'operation Number',
  done: 'Done',
  RS: '{0} RS',
  likeCount: '{0} like',
  joinCount: '{0} join',
  reload: 'Reload',
  logout: 'Logout',
  noServicesFound: 'No services found',
});
