# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eventfull' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #eventfull pods
  rn_path = '../node_modules/react-native'
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', :path => rn_path, :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTLinkingIOS', # Need for gesture
    'RCTGeolocation',
    'RCTImage',
    'RCTActionSheet',
    # Add any other subspecs you want to use in your project
  ]

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'
  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'
  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'


  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'


  target 'eventfullTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eventfull-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eventfull-tvOS

  target 'eventfull-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
